# Generated by Django 5.0.6 on 2024-12-06 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='datejoined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mother',
        ),
    ]
